[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "penglang"
version = "0.9.0"
description = "a nonserious language module for penguins"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "bebeday10"}
]
dependencies = [
    "rich",
    "ascii-magic",
    "pygame-ce"
]
license = "MIT"
keywords = [
    "language",
    "penguin",
    "nonserious",
    "fun",
    "programming",
    "dsl",
    "satisfying",
    "beginners",
    "learners",
    "terminal",
    "esolang",
    "coffee",
    "vending-machine",
    "karaoke",
    "nice",
    "curious",
    "coins",
    "safe-coin-place"
    ]

[project.urls]
Homepage = "https://github.com/bebeday10/penglang"
Repository = "https://github.com/bebeday10/penglang"
Issues = "https://github.com/bebeday10/penglang/issues"

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]

nothing = []